CREATE DATABASE teste01 ON PRIMARY
(NAME = teste01,
FILENAME = 'C:\boson-treinamentos-sql-server\teste01.mdf',
SIZE = 6MB,
MAXSIZE = 15MB,
FILEGROWTH = 10%)
LOG ON (
NAME = teste01_log,
FILENAME = 'C:\boson-treinamentos-sql-server\teste01.ldf',
SIZE = 1MB,
FILEGROWTH =1MB)
GO

-- CONSULTAR BANCOS EXISTENTES
/*
COMENTÁTRIO DE MÚLTIPLAS LINHAS
*/
SELECT name
FROM master.sys.databases
ORDER BY name;

-- PROCEDURE PRA CONSULTAR OS BANCOS EXISTENTES
EXEC sp_databases;

-- SELECIONANDO O BANCO
USE teste01;

-- OBTER INFORMAÇÕES SOBRE UM BANCO ESPECÍFICO
EXEC sp_helpdb teste01;

-- EXCLUINDO O BANCO
DROP DATABASE IF EXISTS teste01;

-- EXCLUINDO BANCO EM USO
USE MASTER
GO
ALTER DATABASE teste01
SET SINGLE_USER WITH ROLLBACK IMMEDIATE
DROP DATABASE teste01;
