/*
FUNÇÕES UDF

PODEMOS CRIAR FUNÇÕES (USER-DEFINED-FUNCTIONS / UDFS) PARA REALIZAR DIVERSAS TAREFAS NO BANCO DE DADOS, TAIS COMO:

- INSERIR LÓGICA COMPLEXA EM UMA CONSULTA
- CRIAR NOVAS FUNÇÕES PARA EXPRESSÕES COMPLEXAS
- SUBSTITUIR VIEWS COM A VANTAGEM DE ACEITAR PARÂMETROS

AS FUNÇÕES UDF PODEM SER ESCALARES OU TABULARES (COM VALOR DE TABELA):

- FUNÇÃO UDF ESCALAR: RETORNA UM VALOR ÚNICO
- FUNÇÃO UDF TABULAR: RETORNA UMA TABELA DE VALORES
*/

-- FUNÇÃO ESCALAR

CREATE FUNCTION valor_total (@inferior SMALLINT, @superior SMALLINT)
RETURNS REAL
AS 
BEGIN
	DECLARE @media REAL
	SELECT @media = AVG(PrecoLivro)
	FROM Livro
	WHERE IdLivro BETWEEN @inferior AND @superior
	RETURN @media;
END

SELECT dbo.valor_total (101,105) AS Total;

-- FUNÇÃO TABULAR

CREATE FUNCTION retorna_itens (@valor REAL)
RETURNS TABLE
AS
RETURN (
	SELECT L.NomeLivro, A.NomeAssunto, E.NomeEditora
	FROM Livro AS L
	INNER JOIN Assunto AS A ON L.IdAssunto = A.IdAssunto
	INNER JOIN Editora AS E ON L.IdEditora = E.IdEditora
	WHERE L.PrecoLivro > @valor
);

SELECT NomeLivro, NomeAssunto
FROM dbo.retorna_itens (62.00);

-- EXCLUINDO UMA FUNÇÃO

DROP FUNCTION retorna_itens;

-- FUNÇÕS DE DATA E HORA

SELECT GETDATE() AS 'Data e hora atuais';
SELECT GETUTCDATE() AS 'Data e hora atuais';
SELECT CURRENT_TIMESTAMP;

SELECT YEAR(GETDATE()) AS ANO;
SELECT MONTH(GETDATE()) AS MES;
SELECT DAY(GETDATE()) AS DIA;

-- DATEDIFF

SELECT DATEDIFF (hh, GETUTCDATE(), GETDATE()) AS 'UTC Brasília';
SELECT DATEDIFF(dd, '1980-12-15', GETDATE()) AS 'Quantidade de dias passados desdes de 15/12/1980';

-- DATEPART

SELECT DATEPART(YYYY, DataPub) AS 'Ano de lançamento', DATEPART(DD, DataPub) AS 'Dia', DATENAME(MM, DataPub) AS	'Mês'
FROM Livro
WHERE IdLivro = 105;

-- DATEADD

SELECT DataPub AS 'Publicação nos EUA', DATEADD(DD,50,DataPub) AS 'Publicação no Brasil'
FROM Livro
WHERE IdLivro = 104;

-- CONVERT

SELECT CONVERT(VARCHAR(10), GETDATE(),108), Hoje;
SELECT NomeLivro AS Título, CONVERT(VARCHAR(10), DataPub,103) Publicação
FROM Livro
WHERE DataPub >= CONVERT(VARCHAR(10), '10/10/2015',103);

-- FUNÇÕES DE MANIPULAÇÃO DE STRINGS

--FUNÇÃO LEN (EXIBE A QUANTIDADE DE CARACTERES):

SELECT NomeLivro, LEN(NomeLivro) 'Quantidade de caracteres do nome do livro'
FROM Livro

SELECT NomeLivro, ISBN13, LEN(ISBN13) 'Quantidade de caracteres do ISBN'
FROM Livro
WHERE LEN(ISBN13) <> 13;

-- FUNÇÃO LOWER E UPPER  (PERMITEM CONVERTER OS CARACTERES DE UMA STRING PARA LETRAS MINÚSCULAS E MAIÚSCULAS, RESPECTIVAMENTE):

SELECT LOWER(NomeLivro) 'Nome minúsculo'
FROM Livro

SELECT UPPER(NomeAssunto) 'Nome maiúsculo'
FROM Assunto

INSERT INTO Autor (NomeAutor, SobrenomeAutor)
VALUES (UPPER('Fábio'), UPPER('dos Reis'));

SELECT * FROM Autor;

-- FUNÇÕES LTRIM, RTRIM, TRIM (SÃO USADAS PARA REMOVER ESPAÇOS EM BRANCO (OU CARACTERES ESPECÍFICOS) NO INÍCIO, NO FINAL OU EM AMBOS OS LADOS DE UMA STRING.
-- ÚTEIS QUANDO SE DESEJA LIMPAR OU PADRONIZAR DADOS TEXTUAIS

SELECT RTRIM(NomeLivro) 'Livro sem espaços no começo'
FROM Livro;

INSERT INTO Autor(NomeAutor, SobrenomeAutor)
VALUES(TRIM('   Daniel   '), TRIM('   Craig  '));

--FUNÇÃO REPLACE (USADO PARA SUBSTITUIR TODAS AS OCORRÊNCIAS DE UMA SUBSTRING POR OUTRA DENTRO DE UMA STRING. É ÚTIL PARA REALIZAR AS TRANSFORMAÇÕES EM DADOS DE TEXTO

UPDATE Livro
SET NomeLivro = REPLACE(NomeLivro, '2016', '2022')
WHERE NomeLivro LIKE '%Server 2016%';

SELECT NomeLivro FROM Livro;

UPDATE Editora
SET NomeEditora = UPPER(NomeEditora);

UPDATE Editora
SET NomeEditora = UPPER(LEFT(NomeEditora, 1)) + LOWER(SUBSTRING(NomeEditora,2, LEN(NomeEditora)))
WHERE NomeEditora IS NOT NULL;

SELECT * FROM Editora;

-- FUNÇÃO LEFT/RIGHT (USADO PARA EXTRAIR PARTES DE UMA STRING COM BASE NO NÚMERO DE CARACTERES A PARTIR DA ESQUERDA OU DA DIREITA, RESPECTIVAMENTE):

SELECT ISBN13, RIGHT(ISBN13,4) 'Quatro últimos caracteres do ISBN13'
FROM Livro

-- FUNÇÃO CONCAT (CONCATENA DUAS OU MAIS STRINGS EM UMA  STRING):

SELECT CONCAT('Nadson', 'Oliveira');

SELECT CONCAT(NomeAutor,' ',SobrenomeAutor) 'Nome + sobrenome'
FROM Autor;