/* ÍNDICES (USADOS PARA OTIMIZAR A RECUPERAÇÃO DE DADOS DE TABELAS:
PERMITEM QUE OS REGISTROS RELEVANTES SEJAM ENCONTRADOS MAIS RAÍDAMENTE COM BASE EM DETERMINADOS CRITÉRIOS DE PESQUISA
CLUSTERIZADOS USAM B-TREE, NÃO CLUSTERIZADOS
*/

-- CRIANDO O ÍNDICE:

CREATE INDEX  ind_nome_livro
ON Livro(NomeLivro);

SELECT NomeLivro
FROM Livro;

-- EXIBINDO OS ÍNDICES:

EXEC sp_helpindex Livro;

-- DESABILITANDO ÍNDICES:

ALTER INDEX ind_nome_livro
ON Livro
DISABLE;

-- DESABILITANDO TODOS OS ÍNDICES:

ALTER INDEX ALL ON Livro
DISABLE;

-- REEXIBINDO O ÍNDICE:

ALTER INDEX ind_nome_livro
ON Livro
REBUILD;

-- REEXIBINDO TODOS OS ÍNDICES:

ALTER INDEX ALL ON Livro
REBUILD;

-- EXCLUIR INDEX:

DROP INDEX Livro.ind_nome_livro;