/*
STORED PROCEDURE (SP): LOTES (BATCHES) DE DECLARAÇÕES SQL EXECUTADAS COMO UMA SUBROTINA, PERMITEM CENTRALIZAR LÓGICA DE ACESSO AOS DADOS EM UM ÚNICO LOCAL
FACILITANDO A MANUTENÇÃO E A OTIMIZAÇÃO DE CÓDIGO, USADO PARA VALIDAÇÃO DE DADOS, CONTROLE DE ACESSO, EXECUÇÃO DE DECLARAÇÕES SQL COMPLEXAS E OUTRAS SITUAÇÕES
É POSSÍVEL AJUSTAR PERMISSÕES DE ACESSO AOS USUÁRIOS DEFININDO QUEM PODE OU NÃO EXECUTÁ-LAS
*/
-- CRIANDO OU ALTERANDO A PROCEDURE

CREATE OR ALTER PROCEDURE sp_teste
AS
BEGIN
	SELECT 'Boson Treinamentos' AS Nome;
END
GO

EXEC sp_teste;

CREATE OR ALTER PROCEDURE sp_teste (@p1 AS INT)
AS
BEGIN
	SELECT CONCAT ('Valor: ', @p1) AS Valor;
END
GO

CREATE OR ALTER PROCEDURE sp_LivroValor
AS
BEGIN
	SELECT NomeLivro AS Título, PrecoLivro AS Valor
	FROM Livro;
END
GO 

EXEC sp_LivroValor;

CREATE OR ALTER PROCEDURE sp_LivroValor
AS
BEGIN
	SELECT NomeLivro AS Título, PrecoLivro Valor
	FROM Livro
	WHERE PrecoLivro >= 150.00;
END
GO

EXEC sp_LivroValor;

-- RETORNA O CÓDIGO SQL DA SP

EXEC sp_helptext sp_LivroValor;
EXEC sp_helptext sp_helptext;

-- EXEMPLO DE PROCEDURE COM CRIPTOGRAFIA

CREATE OR ALTER PROCEDURE sp_LivroISBN
WITH ENCRYPTION
AS
BEGIN
	SELECT NomeLivro, ISBN13
	FROM Livro;
END
GO

EXEC sp_LivroISBN;

-- ALTERANDO PROCEDIMENTO USANDO VARIÁVEIS

CREATE OR ALTER PROCEDURE sp_teste (@p1 AS INT)
AS
BEGIN
	SELECT CONCAT ('Valor: ', @p1) AS Valor;
END
GO

EXEC sp_teste 63;

-- OUTRO EXEMPLO

CREATE OR ALTER PROCEDURE sp_LivroValor (@ID SMALLINT)
AS
BEGIN
	SELECT NomeLivro AS Título, PrecoLivro AS Valor
	FROM Livro
	WHERE IdLivro = @ID;
END
GO

EXEC sp_LivroValor 104;

-- OUTRO EXEMPLO

CREATE OR ALTER PROCEDURE sp_teste (@p1 AS INT, @p2 AS VARCHAR(20))
AS
BEGIN
	SELECT @p1 'Parâmetro 01', @p2 AS 'Parâmetro 02';
END
GO 

EXEC sp_teste 55, 'Laranja';
-- OUdd
EXEC sp_teste @p2 = 'Laranja', @p1 = 55;

-- OUTRO EXEMPLO

CREATE OR ALTER PROCEDURE sp_LivroValor (@ID SMALLINT, @Qtde SMALLINT)
AS
BEGIN
	SELECT NomeLivro AS Título, @QTde AS Quantidade, PrecoLivro * @Qtde 'Valor total'
	FROM Livro
	WHERE IdLivro = @ID;
END
GO

EXEC sp_LivroValor 104, 5;

-- OUTRO EXEMPLO

CREATE OR ALTER PROCEDURE sp_cadastra_editora (@nome VARCHAR(50))
AS
BEGIN
	SET NOCOUNT ON
	INSERT INTO Editora (NomeEditora) VALUES (@nome);
END
GO

EXEC sp_cadastra_editora 'Círculo do Livro';
EXEC sp_cadastra_editora 'Makron Books';

SELECT * FROM Editora;

-- DELETANDO UMA PROCEDURE

DROP PROCEDURE sp_LivroValor;
SELECT * FROM Editora;
