/*
STORED PROCEDURE (SP): LOTES (BATCHES) DE DECLARAÇÕES SQL EXECUTADAS COMO UMA SUBROTINA, PERMITEM CENTRALIZAR LÓGICA DE ACESSO AOS DADOS EM UM ÚNICO LOCAL
FACILITANDO A MANUTENÇÃO E A OTIMIZAÇÃO DE CÓDIGO, USADO PARA VALIDAÇÃO DE DADOS, CONTROLE DE ACESSO, EXECUÇÃO DE DECLARAÇÕES SQL COMPLEXAS E OUTRAS SITUAÇÕES
É POSSÍVEL AJUSTAR PERMISSÕES DE ACESSO AOS USUÁRIOS DEFININDO QUEM PODE OU NÃO EXECUTÁ-LAS
*/
-- EXEMPLO 1
CREATE PROCEDURE sp_LivroValor
AS
BEGIN
	SELECT NomeLivro AS Título, PrecoLivro AS Valor
	FROM Livro;
END
GO

EXEC sp_LivroValor;

-- ALTERANDO O PROCEDIMENTO

ALTER PROCEDURE sp_LivroValor
AS
BEGIN
	SELECT NomeLivro AS Título, PrecoLivro Valor
	FROM Livro
	WHERE PrecoLivro >= 150.00;
END
GO

-- RETORNA O CÓDIGO SQL DA SP

EXEC sp_helptext sp_LivroValor;
EXEC sp_helptext sp_helptext;

-- EXEMPLO DE PROCEDURE COM CRIPTOGRAFIA

CREATE OR ALTER PROCEDURE sp_LivroISBN
WITH ENCRYPTION
AS
BEGIN
	SELECT NomeLivro, ISBN13
	FROM Livro;
END
GO

EXEC sp_LivroISBN;

-- ALTERANDO PROCEDIMENTO USANDO VARIÁVEIS

ALTER PROCEDURE sp_LivroValor (@ID SMALLINT)
AS
BEGIN
	SELECT NomeLivro AS Título, PrecoLivro AS Valor
	FROM Livro
	WHERE IdLivro = @ID;
END
GO
EXEC sp_LivroValor 104;

-- OUTRO EXEMPLO

ALTER PROCEDURE sp_LivroValor (@ID SMALLINT, @Qtde SMALLINT)
AS
BEGIN
	SELECT NomeLivro AS Título, @QTde AS Quantidade, PrecoLivro * @Qtde 'Valor total'
	FROM Livro
	WHERE IdLivro = @ID;
END
GO
EXEC sp_LivroValor 104, 5;

